config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get  "/donate",    to: "static_pages#donate"
  get  "/about",   to: "static_pages#about"
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 },
                      presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    # Returns the hash digest of the given string.
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    validates :age, presence: true
    validates :emergencyPhoneNumber, presence: true, length: {maximum: 12}
    validates :teamName, presence: true

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy!

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      log_in user
      redirect_to forwarding_url || user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def donate
    if (params[:button_clicked])
      flash.now[:success] = 'Thank you for donating!'

    
    end
  end
  
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]  
  before_action :admin_user,     only: [:destroy, :promote]

  def index    
    @users = User.paginate(page: params[:page])
  end

def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end

  def promote    
    @user = User.find(params[:id])
    @user.admin = true
    flash[:success] = "User promoted"
    redirect_to users_url, status: :see_other
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :age,
                                   :emergencyPhoneNumber, :teamName)
    
    end
    # Before filters
    
        # Confirms a logged-in user.
        def logged_in_user
          unless logged_in?
            store_location
            flash[:danger] = "Please log in."
            redirect_to login_url, status: :see_other
          end
        end
        # Confirms the correct user.
        def correct_user
          @user = User.find(params[:id])
          redirect_to(root_url, status: :see_other) unless current_user?(@user)
        end
        # Confirms an admin user.
            def admin_user
              redirect_to(root_url, status: :see_other) unless current_user.admin?
            end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end
  
    # Returns the current logged-in user (if any).
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    def current_user?(user)
    user && user == current_user
  end
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end
    # Logs out the current user.
    def log_out
      reset_session
      @current_user = nil
    end
  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Organization Contact: 2907-209-208 &emsp; Email: Fakeemail@fake.com
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "The 5k Charity", root_path, id: "logo" %>
    <nav>
    <div class="navbar-header">
    <button id="hamburger" type="button" class="navbar-toggle collapsed">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <ul id="navbar-menu"
      class="nav navbar-nav navbar-right collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Donate", donate_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" id="account" class="dropdown-toggle">
              Account <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Donate",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>>
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>">
  <p>
    <strong>Content:</strong>
    <%= micropost.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= micropost.user_id %>
  </p>

</div>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
      <%= link_to "Show this micropost", micropost %>
    </p>
  <% end %>
</div>

<%= link_to "New micropost", new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @micropost %>

<div>
  <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
  <%= link_to "Back to microposts", microposts_path %>

  <%= button_to "Destroy this micropost", @micropost, method: :delete %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Mission Statement: To give to those who need it most, and to stand for those who cannot stand for themselves
</p>
<p>
  Who is involved: Wesley Cassel, Rachel Wyatt, Samantha Strutz Siegal, and Joseph Beasley
</p>
<p>
  Where are we located: South Carolina
</p>

app/views/static_pages/donate.html.erb
<% provide(:title, "Donate") %>
<h1>Donate</h1>
<p>
 
  <%= form_with(model: @user) do |f| %>
      <%= f.label "How Much You Would Like To Donate" %>
      <%= f.text_field :amount %>
      
      <%= f.submit "Donate", class: "btn btn-primary" %> 
      <%= hidden_field_tag :button_clicked, true %>
    <% end %>
</p>

app/views/static_pages/home.html.erb
<div class="left">
  <h1>Information About the Charity</h1>
  <h2>
    All donations and food purchases will go towards the Fake Charity Organization, which specializes in helping those in need around the world.
  </h2>
  <h1>
  Information About the 5k Run
</h1>
<h2>
The 5k will take place Tuesday, April 23rd. It will last from 11am to 5pm. Lunch will be provided at 1pm, and water will be proved to runners at specified checkpoints.
</h2>
</div>

<%= image_tag('running.jpg', draggable: "true", id: "runners", width: "600") %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label :emergencyPhoneNumber, "Emergency Phone Number" %>
  <%= f.text_field :emergencyPhoneNumber, class: 'form-control' %>

  <%= f.label :age %>
  <%= f.text_field :age, class: 'form-control' %>


  <%= f.label :teamName, "Team Name" %>
  <%= f.text_field :teamName, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% if current_user.admin? && !current_user?(user) %>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>,
    <%= link_to user.teamName, user %>,
    <%= link_to "DELETE", user, data: { "turbo-method": :delete,
                                        turbo_confirm: "You sure?" } %>,
    <%= link_to "PROMOTE", user, data: { "turbo-method": :promote,
                                        turbo_confirm: "You sure?" } %>
  <% else %>
  <% if user.teamName == current_user.teamName %>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>, 
    <%= link_to user.teamName, user %>
  <% end %>
<% end %>
</li>

app/views/users/admin.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        Hello Admin 
        <%= @user.name %>,
        <%= @user.teamName %>
      </h1>
      <body>
      <table class = "table" style="max-width:15rem;">
      <thead class = "thead-dark">
        <th>Time </th>
        <th>Activity</th>
      </thead>
      <tbody>
      <tr>
        <td>11am </td>
        <td>Race Starts</td>
      </tr>
      <tr>
        <td>1pm</td>
        <td>Lunch</td>
      </tr>
      <tr>
        <td>5pm</td>
        <td>Race Ends</td>
      </tr>
      </tbody>
    </table>
      </body>
      <li><%= link_to "Users", users_path %></li>
    </section>
    <%= link_to image_tag("5k map.png", alt: "Running", width: "300") %>
  </aside>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.admin? %>
          <%= gravatar_for @user %>
          Hello Admin 
          <%= @user.name %>,
          <%= @user.teamName %>
        <% else %>
          <%= gravatar_for @user %>
          Hello 
          <%= @user.name %>,
          <%= @user.teamName%>
          <% end %>
      </h1>
      <body>
      <table class = "table" style="max-width:15rem;">
        <thead class = "thead-dark">
          <th>Time </th>
          <th>Activity</th>
        </thead>
        <tbody>
        <tr>
          <td>11am </td>
          <td>Race Starts</td>
        </tr>
        <tr>
          <td>1pm</td>
          <td>Lunch</td>
        </tr>
        <tr>
          <td>5pm</td>
          <td>Race Ends</td>
        </tr>
        </tbody>
      </table>
      </body>
      <li><%= link_to "Users", users_path %></li>
    </section>
    <%= link_to image_tag("5k map.png", alt: "Running", width: "300") %>
  </aside>
</div>